{{- if .Values.microfunctionscontroller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microfunctions.microfunctionscontroller.serviceAccountName" . }}
  labels:
    {{- include "microfunctions.microfunctionscontroller.labels" . | nindent 4 }}
  {{- with .Values.microfunctionscontroller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
