apiVersion: v2
name: microfunctions
description: MicroFunctions is open-source serverless platform bthat lets you deploy small bits of code without having to worry about the underlying infrastructure plumbing. It leverages Kubernetes  resources to provide auto-scaling, API routing, monitoring, troubleshooting and supports every programming language. (Nodejs,Go,python,..).

keywords:
  - backend
  - serverless
  - platform
  - functions
home: https://microfunctions.io/
icon: https://camo.githubusercontent.com/63459c2b28d67165026260c9c986e84b276e5c548122d745da9762ae3bd11fb1/687474703a2f2f7777772e6d6963726f66756e6374696f6e732e696f2f77702d636f6e74656e742f75706c6f6164732f323032302f30372f4e65772d50726f6a6563742d332e706e67
sources:
  - https://github.com/microfunctionsio/microfunctions-helm

type: application

version: 0.1.0

appVersion: 0.1.0

dependencies:
  - name: mongodb
    version: 7.8.10
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 7.6.9
    repository: https://charts.bitnami.com/bitnami
  - name: nginx-ingress-controller
    condition: nginx-ingress-controller.enabled
    version: 7.5.0
    repository: https://charts.bitnami.com/bitnami
  - name: metrics-server
    condition: metrics-server.enabled
    version: 5.3.1
    repository: https://charts.bitnami.com/bitnami
  - name: cert-manager
    condition: cert-manager.enabled
    version: 1.2.0
    repository: https://charts.jetstack.io
  - name: kong
    condition: kong.enabled
    version: 3.4.5
    repository: https://charts.bitnami.com/bitnami
