apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microfunctions.microfunctionsauth.fullname" . }}
  labels:
    {{- include "microfunctions.microfunctionsauth.labels" . | nindent 4 }}
spec:
{{- if not .Values.microfunctionsauth.autoscaling.enabled }}
  replicas: {{ .Values.microfunctionsauth.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "microfunctions.microfunctionsauth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.microfunctionsauth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "microfunctions.microfunctionsauth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "microfunctions.name" . }}-{{ .Values.microfunctionsauth.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.microfunctionsauth.image.repository }}:{{ .Values.microfunctionsauth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.microfunctionsauth.image.pullPolicy }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.mongodbUsername | quote }}
            - name: MONGODB_DB
              value: {{ .Values.mongodb.mongodbDatabase | quote }}
            - name: MONGODB_HOST
              value: {{ include "microfunctions.mongodb.fullname" . }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: RABBIT_USER
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: RABBIT_HOST
              value: {{ include "microfunctions.rabbitmq.fullname" . }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "microfunctions.fullname" . }}-auth
                  key: auth-jwt-secret
            - name: JWT_SECRET_EXPIRES_IN
              value: {{ .Values.microfunctionsauth.JwtSecretExpiresIn | quote }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
