apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microfunctions.fullname" . }}-auth
  labels:
    app: {{ template "microfunctions.name" . }}
    chart: {{ template "microfunctions.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.microfunctionsauth.JwtSecret }}
  auth-jwt-secret:  {{ .Values.microfunctionsauth.JwtSecret | b64enc | quote }}
  {{- else }}
  auth-jwt-secret: {{ randAlphaNum 26 | b64enc | quote }}
  {{- end }}

