{{- if .Values.microfunctionsconsole.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microfunctions.microfunctionsconsole.serviceAccountName" . }}
  labels:
    {{- include "microfunctions.microfunctionsconsole.labels" . | nindent 4 }}
  {{- with .Values.microfunctionsconsole.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
