apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microfunctions.fullname" . }}-cluster
  labels:
    app: {{ template "microfunctions.name" . }}
    chart: {{ template "microfunctions.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.microfunctionsauth.JwtSecret }}
  cluster-secret:  {{ .Values.microfunctionscluster.ClusterSecret | b64enc | quote }}
  {{- else }}
  cluster-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

